id = "T0001"
title = "Implement TOML configuration parsing"
status = "Open"
type = "Feature"

[project]
id = "P0001"

[assignee]
name = "Jane Doe"
email = "jane.doe@example.com"

[estimated_time]
hours = 8
minutes = 30
