id = "T0002"
title = "Implement TOML configuration parsing in a much cooler way"
status = "Backlog"
type = "Feature"

[project]
id = "P0001"

[assignee]
name = "Jane Doe"
email = "jane.doe@example.com"

[estimated_time]
hours = 8
minutes = 30
