id = "T0003"
title = "Get some 3 way action"
status = "InProgress"
type = "Bug"
description = "Get some 3 way action for the IRDB project"

[project]
id = "P0002"

[estimated_time]
hours = 8
minutes = 30

[assignee]
email = "jane.doe@example.com"
name = "Jane Doe"
